---
version: "2.1"
volumes:
  emucfg:
    driver: local
  emudata:
    driver: local
services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SUBFOLDER=/ #optional
    volumes:
      - emucfg:/config
      - emudata:/data
    ports:
      - 3000:3000
      - 8082:80
      - 4001:4001 #optional
    restart: unless-stopped