version: "3"
services:

  freeciv-web:
    image: freeciv/freeciv-web
    restart: "unless-stopped"
    build: .
    container_name: freeciv-web
    command: ["sleep", "infinity"]
    volumes:
      - "fciv_data:/var/lib/tomcat10/webapps/data"
    ports:
      - "8084:80"
      - "4002:4002"
      - "6000-6009:6000-6009"
      - "7000-7009:7000-7009"
      - "8085:8080"
    user: docker

volumes:
  fciv_data: